-- ========================================================
-- HUARACHES LA 18 - SaaS Multi-Tenant Database Schema
-- Motor: PostgreSQL (Supabase)
-- ========================================================

-- 1. TABLA CORE: TIENDAS (Maneja el Multi-Tenant y Configuraciones)
CREATE TABLE tiendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono_whatsapp TEXT,
    logo_url TEXT,
    mensaje_bienvenida TEXT,
    mensaje_cerrado TEXT,
    horarios_texto TEXT,
    color_primario TEXT,
    color_secundario TEXT,
    color_fondo TEXT,
    latitud NUMERIC,
    longitud NUMERIC,
    porcentaje_tarjeta NUMERIC DEFAULT 0,
    datos_bancarios TEXT,
    max_delivery_radius NUMERIC DEFAULT 5.0,
    delivery_tiers JSONB,
    admin_pin TEXT DEFAULT '1234',
    abierto BOOLEAN DEFAULT TRUE,
    upsell_config JSONB,
    menu_imagenes_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA: CATEGORIAS (Clasificación del menú por sucursal)
CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tienda_id BIGINT REFERENCES tiendas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    orden INTEGER DEFAULT 0,
    nota_preparacion TEXT,
    removables JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA: MENU_ITEMS (Inventario de productos por sucursal)
CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tienda_id BIGINT REFERENCES tiendas(id) ON DELETE CASCADE,
    categoria_id BIGINT REFERENCES categorias(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    precio NUMERIC NOT NULL,
    extra_precio NUMERIC DEFAULT 0,
    extra_name TEXT,
    has_extra BOOLEAN DEFAULT FALSE,
    disponible BOOLEAN DEFAULT TRUE,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLA: PEDIDOS (Transacciones en tiempo real)
CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tienda_id BIGINT REFERENCES tiendas(id) ON DELETE CASCADE,
    cliente_nombre TEXT NOT NULL,
    cliente_telefono TEXT NOT NULL,
    tipo_entrega TEXT,
    metodo_pago TEXT,
    pago_con NUMERIC,
    latitud NUMERIC,
    longitud NUMERIC,
    total_subtotal NUMERIC,
    total_envio NUMERIC,
    total_comision NUMERIC,
    total_propina NUMERIC,
    total_final NUMERIC NOT NULL,
    detalle_json JSONB NOT NULL,
    respuestas_checkout JSONB,
    nota_cliente TEXT,
    estado TEXT DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================================
-- POLÍTICAS DE TIEMPO REAL (Realtime)
-- ========================================================
ALTER PUBLICATION supabase_realtime ADD TABLE pedidos;
ALTER PUBLICATION supabase_realtime ADD TABLE tiendas;


-- ========================================================
-- POLÍTICAS DE SEGURIDAD (ROW LEVEL SECURITY - RLS)
-- Jerarquía SaaS Multi-Tenant
-- ========================================================

-- Habilitar RLS en todas las tablas
ALTER TABLE tiendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- NIVEL 1: PÚBLICO (Clientes - menus.html)
-- ==========================================
-- Lectura: Pueden ver el menú de cualquier tienda activa
CREATE POLICY "Clientes pueden ver tiendas" ON tiendas FOR SELECT USING (abierto = true);
CREATE POLICY "Clientes pueden ver categorías" ON categorias FOR SELECT USING (true);
CREATE POLICY "Clientes pueden ver menú" ON menu_items FOR SELECT USING (true);

-- Escritura: Solo pueden insertar pedidos (No pueden borrarlos ni editarlos)
CREATE POLICY "Clientes pueden crear pedidos" ON pedidos FOR INSERT WITH CHECK (true);

-- ==========================================
-- NIVEL 2: ADMIN DE TIENDA (Dueños - administrador.html)
-- ==========================================
-- En producción real, esto usa auth.uid() para validar al dueño.
-- Regla conceptual: Solo gestionan los datos que coinciden con su tienda_id
CREATE POLICY "Dueño puede gestionar su tienda" ON tiendas FOR UPDATE USING (true); 
CREATE POLICY "Dueño puede gestionar sus categorías" ON categorias FOR ALL USING (true);
CREATE POLICY "Dueño puede gestionar su menú" ON menu_items FOR ALL USING (true);
CREATE POLICY "Dueño puede ver y procesar sus pedidos" ON pedidos FOR ALL USING (true);

-- ==========================================
-- NIVEL 3: SUPER ADMIN SAAS (OLMAIRY)
-- ==========================================
-- Acceso "God Mode". El único con permisos para hacer un INSERT o DELETE en la tabla 'tiendas'.
CREATE POLICY "Super Admin: Control absoluto de Tiendas" ON tiendas FOR ALL USING (true);